apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-11-29T02:03:08Z"
  generation: 1
  labels:
    app: hello-server
  name: hello-server
  namespace: default
  resourceVersion: "3852"
  uid: bcc9f102-54c2-48aa-9818-d594812581b3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-server
    spec:
      serviceAccountName: gke-service-account
      containers:
      - image: us-central1-docker.pkg.dev/cloudcomputingcourse-398918/hw4-ds561-docker-repo/hw4-image:tag2
        imagePullPolicy: IfNotPresent
        name: hw4-image
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-11-29T02:03:39Z"
    lastUpdateTime: "2023-11-29T02:03:39Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-11-29T02:03:08Z"
    lastUpdateTime: "2023-11-29T02:03:39Z"
    message: ReplicaSet "hello-server-6db9578f7f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
